---
version: '3.4'
networks:
  default_net:
    external: true
services:
  proxy:
    image: estenrye/traefik:latest
    environment:
      - TLD=${TLD}
      - EMAIL=${EMAIL}
      - CONSUL_HTTP_TOKEN=${TRAEFIK_CONSUL_TOKEN}
    networks:
      - default_net
    ports:
      - target: 80
        published: 80
        mode: ingress
      - target: 443
        published: 443
        mode: ingress
      - target: 8080
        published: 8080
        mode: ingress
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: global
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 30s
      restart_policy:
        condition: any
        delay: 5s
        window: 120s
      placement:
        constraints:
          - node.role == manager
