---
version: '3.4'
networks:
  default_net:
    external: true
services:
  proxy_init:
    image: traefik:1.6.0-rc6
    environment: 
      - CONSUL_HTTP_TOKEN=${TRAEFIK_CONSUL_TOKEN}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - AWS_HOSTED_ZONE_ID=${AWS_HOSTED_ZONE_ID}
    command:
      - "storeconfig"
      - "--debug=true"
      - "--loglevel=DEBUG"
      - "--api"
      - "--entrypoints=Name:http Address::80 Redirect.EntryPoint:https"
      - "--entrypoints=Name:https Address::443 TLS"
      - "--entrypoints=Name:traefik Address::8080"
      - "--defaultentrypoints=http,https"
      - "--acme"
      - "--acme.storage=traefik/acme/account"
      - "--acme.entryPoint=https"
      - "--acme.dnsChallenge"
      - "--acme.dnsProider=route53"
      - "--acme.dnschallenge.delaybeforecheck=10"
      - "--acme.OnHostRule=true"
      - "--acme.onDemand=false"
      - "--acme.email=${EMAIL}"
      - "--docker"
      - "--docker.swarmmode=true"
      - "--docker.domain=${TLD}"
      - "--docker.exposedbydefault=false"
      - "--docker.watch=true"
      - "--consul"
      - "--consul.tls"
      - "--consul.tls.ca=/consul/certs/fullchain.pem"
      - "--consul.tls.key=/consul/certs/privkey.pem"
      - "--consul.tls.cert=/consul/certs/cert.pem"
      - "--consul.endpoint=consul-server.${PRIVATE_HOSTED_ZONE}:8500"
      - "--consul.prefix=traefik"
    deploy:
      restart_policy:
        condition: on-failure  
      placement:
        constraints:
          - node.role == manager
    networks:
      - default_net
    volumes:
      - type: bind
        source: /home/docker/consul/certs
        target: /consul/certs
  proxy:
    image: traefik:1.6.0-rc6
    command:
      - "--consul"
      - "--consul.tls"
      - "--consul.tls.ca=/consul/certs/fullchain.pem"
      - "--consul.tls.key=/consul/certs/privkey.pem"
      - "--consul.tls.cert=/consul/certs/cert.pem"
      - "--consul.endpoint=consul-server.${PRIVATE_HOSTED_ZONE}:8500"
      - "--consul.prefix=traefik"
      - "--consul.watch=true"
    environment:
      - CONSUL_HTTP_TOKEN=${TRAEFIK_CONSUL_TOKEN}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - AWS_HOSTED_ZONE_ID=${AWS_HOSTED_ZONE_ID}
    networks:
      - default_net
    ports:
      - target: 80
        published: 80
        mode: ingress
      - target: 443
        published: 443
        mode: ingress
      - target: 8080
        published: 8080
        mode: ingress
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - type: bind
        source: /home/docker/consul/certs
        target: /consul/certs
    deploy:
      mode: global
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 30s
      restart_policy:
        condition: any
        delay: 5s
        window: 120s
      placement:
        constraints:
          - node.role == manager
