---
version: '3.3'
networks:
  default_net:
    external: true
secrets:
  agent-config:
    external:
      name: consul.agent.config.json
  server-config:
    external:
      name: consul.server.config.json
  # ca:
  #   external:
  #     name: ca.cert.pem
  # cert:
  #   external:
  #     name: consul.cert.pem
  # key:
  #   external:
  #     name: consul.key.pem
  
services:
  # Deploy the consul server instances
  server:
    image: consul:latest
    networks:
      default_net:
        aliases:
          - consul.server
    ports:
      - target: 8500
        published: 8500
        protocol: tcp
        mode: host
    # Start the consul server with the given configuration
    command: "consul agent -config-file /run/secrets/config.json"
    # Mount the data volumes to the container.
    volumes:
      - type: bind
        source: /home/docker/consul/data
        target: /consul/data
    # Mount the configuration and TLS certificates
    secrets:
      - source: server-config
        target: config.json
      # - source: ca
      #   target: ca-chain.cert.pem
      # - source: cert
      #   target: consul.cert.pem
      # - source: key
      #   target: consul.key.pem
    # Deploy the consul server on all servers which are managers.
    # Use DNS Round Robin instead VIP for discovery. This ensures we get all running
    # consul server instances when querying consul.server
    deploy:
      mode: global
      endpoint_mode: dnsrr
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 30s
      restart_policy:
        condition: any
        delay: 5s
        window: 120s
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.backend=consul.server
        - traefik.docker.network=default_net
        - traefik.frontend.rule=Host:consul-ui.${TLD}
        - traefik.enable=true
        - traefik.port=8500
        - traefik.protocol=http
  # Deploy the consul agent instances
  agent:
    image: consul:latest
    networks:
      default_net:
        aliases:
          - consul.server
    ports:
      - target: 8500
        published: 8500
        protocol: tcp
        mode: host
     # Start the consul agent with the given configuration          
    command: "consul agent -config-file /run/secrets/config.json"
    # Mount the configuration and data volumes to the container.
    # Mount the data volumes to the container.
    volumes:
      - type: bind
        source: /home/docker/consul/data
        target: /consul/data
    # Mount the configuration and TLS certificates
    secrets:
      - source: agent-config
        target: config.json
      # - source: ca
      #   target: ca-chain.cert.pem
      # - source: cert
      #   target: consul.cert.pem
      # - source: key
      #   target: consul.key.pem
    # Deploy the consul agent on all servers which are workers.
    # Use DNS Round Robin instead VIP for discovery.  
    deploy:
      mode: global
      endpoint_mode: dnsrr
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 30s
      restart_policy:
        condition: any
        delay: 5s
        window: 120s
      placement:
        constraints:
          - node.role == worker
      labels:
        - traefik.backend=consul.client
        - traefik.docker.network=default_net
        - traefik.frontend.rule=Host:consul-api.${TLD}
        - traefik.enable=true
        - traefik.port=8500
        - traefik.protocol=http